### PR TITLE
add vendor-device ID for PioneerDJ/DJM-900NXS2

### PR DESCRIPTION
**Pull request by thisnickistaken**

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Thank you for this addition, would you mind uppercasing the ID so its consistent with the rest of the table?

**Comment by thisnickistaken** [comment]
Not at all. Done.

**Comment by Swiftb0y** [comment]
Thank you very much

**Comment by Swiftb0y** [comment]
I'd like to credit you for your addition, how would you prefer to be credited? (under what name? anything else?)

**Comment by thisnickistaken** [comment]
Thanks! My name is Ashley Skye. When you say "anything else", what do you
mean?

**Comment by Swiftb0y** [comment]
anything else would be something like a public email or a link to your blog, or something in case you have anything like that and want it mentioned.

**Pull request merged**
